version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Download and Upload File"
          command: |
            wget https://sourceforge.net/projects/jack-the-ripper/files/onclite/CrDroid/crDroidAndroid-12.1-20220920-onclite-v8.9.zip/download -O Crdroid.zip
            curl -T Crdroid.zip oshi.at

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
