version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Download and Upload File"
          command: |
            apt install speedtest-cli
            speedtest

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
